spring.application.name=neptuno
server.port=8081

# MySQL Configuration (Restored)
spring.datasource.url=jdbc:mysql://localhost:3306/neptuno
spring.datasource.username=root
spring.datasource.password=12345

# Forzar la actualizacion del schema en lugar de solo validarlo
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.com.idat.pe=DEBUG

# JWT Configuration
jwt.secret=NeptunoClusSeguroSecretKeyParaJWTPorFavor2024ConMaximaSeguridad
jwt.expiration=36000000
